image: ubuntu:latest

stages:
  - build
  - deploy

variables:
  NODEJS_VERSION: "14"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - nvm install $NODEJS_VERSION
  - nvm use $NODEJS_VERSION
  - node -v
  - npm -v

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - git config --global credential.helper store
    - git config --global user.name "Roman9456"
    - git config --global user.email "smolyakov_ra@mail.ru"
    - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
    - ls dist 
    - npx gh-pages -d dist -u "Roman9456 <smolyakov_ra@mail.ru>"
  only:
    - main
