image: Ubuntu1804

branches:
  only:
    - main

environment:
  matrix:
    - nodejs_version: "14"

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install $nodejs_version
  - nvm use $nodejs_version

install:
  - echo "Installing dependencies..."
  - npm install

build_script:
  - echo "Building the project..."
  - npm run build

artifacts:
  - path: dist
    name: artifact

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - git clone git@github.com:Roman9456/Whack-a-Goblin.git
  - cd Whack-a-Goblin
  - git checkout main
  - git checkout gh-pages
  - git rm -r .
  - cp -R ../dist/* .
  - git add .
  - git config user.name "Roman9456"
  - git config user.email "smolyakov_ra@mail.ru"
  - git commit -m "Deploying to GitHub Pages"
  - git push origin gh-pages
