image: Ubuntu1804

branches:
  only:
    - main

environment:
  matrix:
    - nodejs_version: "14"

init:
  - ps: Install-Product node $env:nodejs_version

install:
  - npm install

build_script:
  - npm run build

artifacts:
  - path: dist
    name: artifact

deploy_script:
  - git clone https://github.com/Roman9456/Whack-a-Goblin.git
  - cd Whack-a-Goblin
  - git checkout gh-pages
  - cp -R ../dist/* .
  - git add .
  - git config user.name "Roman9456"
  - git config user.email "smolyakov_ra@mail.ru"
  - git commit -m "Deploying to GitHub Pages"
  - git push https://${GITHUB_TOKEN}@github.com/Roman9456/Whack-a-Goblin.git gh-pages



