image: Ubuntu1804

branches:
  only:
    - main

environment:
  matrix:
    - nodejs_version: "14"

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install $nodejs_version
  - nvm use $nodejs_version

install:
  - echo "Installing dependencies..."
  - npm install

build_script:
  - echo "Building the project..."
  - npm run build

artifacts:
  - path: dist
    name: artifact

deploy_script:
  - echo "Configuring Git..."
  - git config --global credential.helper store
  - git config --global user.name "Roman9456"
  - git config --global user.email "smolyakov_ra@mail.ru"
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - echo "Contents of dist directory:"
  - ls -al dist
  - echo "Deploying to GitHub Pages..."
  - npx gh-pages -d dist -u "Roman9456 <smolyakov_ra@mail.ru>"
  - echo "Deployment complete."